### ISSUE TITLE
Lab Report 2 Feedback

### ISSUE THREAD

**Issue by enzohnnn** [abhishekg999/cse15l-lab-reports#2]
**Bug/Input 1**
- [X] Commit screenshot for bug/input 1
- [X] Link to test file for bug/input 1
- [x] Symptom shown as command + output for bug/input 1
- [x] Description of relationship between bug, symptom, and input for bug/input 1

**Bug/Input 2**
- [X] Commit screenshot for bug/input 2
- [X] Link to test file for bug/input 2
- [x] Symptom shown as command + output for bug/input 2
- [x] Description of relationship between bug, symptom, and input for bug/input 2

**Bug/Input 3**
- [X] Commit screenshot for bug/input 3
- [X] Link to test file for bug/input 3
- [x] Symptom shown as command + output for bug/input 3
- [x] Description of relationship between bug, symptom, and input for bug/input 3

Additional comments from your grader:
There is a bit to fix there in my opinion. 
Firstly, I think you could better separate your different bugs into 3 parts using headers or titles or something. 
Then, you're missing your symptoms shown as a command + output. A simple terminal screenshot would be fine.
Lastly, I really think you could've written a lot more for your descriptions for each bug. It's hard to tell what is wrong, how the test failed, how you fixed, it, etc etc.

Feel free to comment below if you have any questions about the rubric/feedback.

**Comment by abhishekg999** [comment]
commits have been made
